# Generated by Django 3.2.11 on 2022-08-31 00:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FizzBuzz',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('useragent', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-creation_date', '-updated_date'],
                'abstract': False,
            },
        ),
    ]
