# Generated by Django 3.2.11 on 2022-08-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fizzbuzz_creator', '0002_auto_20220831_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fizzbuzz',
            old_name='pkid',
            new_name='fizzbuzz_id',
        ),
    ]
